language: python

python:
  - '2.7'

branches:
  only:
    - master
    - develop

services: mongodb

install:
  - python setup.py develop
  - pip install -r requirements.txt --use-mirrors

script: python setup.py nosetests
