language: python

python:
  - '2.7'

branches:
  only:
    - master
    - flask-setup

install:
  - python setup.py install
  - pip install -r requirements.txt --use-mirrors
script: python setup.py test

notifications:
  irc:
    on_success: change
    on_failure: change
